{
    "language": "cpp",
    "dist": "trusty",
    "sudo": "required",
    "before_cache": [
        "mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}' | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'\n"
    ],
    "cache": {
        "bundler": true,
        "directories": [
            "$HOME/docker"
        ]
    },
    "services": [
        "docker"
    ],
    "before_install": [
        "if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c \"zcat {file} | docker load\"; fi"
    ],
    "install": [
        "docker build -t cracen2 ."
    ],
    "script":[
        "docker -v `pwd`:/cracen2 run cracen2"
    ]
}
