language: cpp
sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libboost-all-dev
      env:
        - CMAKE_CXX_COMPILER="g++-6"

#    - os: linux
#      addons:
#        apt:
#          sources:
#            - llvm-toolchain-trusty-4.0
#          packages:
#            - clang-4.0
#            - libboost-all-dev
#      env:
#        - CMAKE_CXX_COMPILER="clang++-4.0"

before_script:
    mkdir build;
    cd build;
    cmake -DCMAKE_CXX_COMPILER="$CMAKE_CXX_COMPILER" .. && make

script:
    cd build;
    ctest
